import { WorkflowPipeline } from '@/types';

export const INDUSTRY_WORKFLOW_PRESETS: WorkflowPipeline[] = [
  {
    id: 'preset-uk-influencer-podcast',
    name: 'UK/EU Persona 1 — Podcast Relationship & Mindset (Master)',
    nicheType: 'podcast_debate',
    description: '4-Clip 40s serialized podcast reel. Locked studio frame with Shure SM7B mic, off-camera gaze, level head, and signature cheek mole identity.',
    personaSubjectAnchor: '24yo woman with brunette hair, green eyes, natural subtle makeup, signature cheek beauty mole on cheekbone. Gold layered necklace, small stud earrings, off-shoulder dark knit top. Warm, relatable, authentic real skin texture with visible pores. Uses attached Reference Image for face and identity.',
    cameraShootingStyle: '35mm cinema lens, locked static tripod camera with faint handheld micro-drift — head held straight/level, gaze directed slightly off-camera, no push-ins.',
    hookArchetype: 'curiosity_gap',
    pacingCadence: 'measured_cinematic_16w',
    audioFoleyMood: 'Warm acoustic studio presence, Shure SM7B proximity vocal tone, natural breath intake, subtle lo-fi tape hiss.',
    visualStylePreset: 'Hyper-Realistic Cinematic',
    defaultLocations: ['Intimate Podcast Studio with warm ambient lamp glow and blurred bookshelf background'],
    isPinned: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'preset-influencer-ugc',
    name: 'AI Influencer / UGC Viral Vlogger',
    nicheType: 'ai_influencer_ugc',
    description: 'Direct-to-camera vertical selfie vlogger with natural ring lighting, high retention curiosity hooks, and fast pacing.',
    personaSubjectAnchor: '24yo charismatic female digital creator with natural makeup, oversized pastel crewneck, dynamic expressive facial eye contact, realistic skin texture.',
    cameraShootingStyle: 'Handheld iPhone 16 Pro 4K front-facing camera, natural subtle hand shake, eye-level selfie framing, warm ring-light illumination.',
    hookArchetype: 'curiosity_gap',
    pacingCadence: 'rapid_tiktok_22w',
    audioFoleyMood: 'Crisp proximity vocal isolation, subtle apartment background ambience, punchy sound effect pop on key words.',
    visualStylePreset: 'Hyper-Realistic Cinematic',
    defaultLocations: ['Sunlit Modern Apartment Living Room', 'Minimalist Aesthetic Vanity Desk'],
    isPinned: false,
    createdAt: '2026-01-01T00:00:00.000Z',
  },

  {
    id: 'preset-talking-object',
    name: 'Talking 3D Mascot / Anthropomorphic Object',
    nicheType: 'talking_object',
    description: 'Expressive everyday object or 3D animated character with Pixar-grade micro-expressions, humor, and relatable human struggles.',
    personaSubjectAnchor: 'Weathered ceramic espresso mug with glossy glaze, warm rising steam, expressive animated facial micro-expressions, lively cartoonish personality.',
    cameraShootingStyle: 'Macro 100mm tabletop lens, shallow depth of field, low-angle hero framing looking up at the object, soft morning key light.',
    hookArchetype: 'shock_reversal',
    pacingCadence: 'measured_cinematic_16w',
    audioFoleyMood: 'Ceramic clink Foley, steam hiss, high-clarity expressive character voice pitch, comedic musical stingers.',
    visualStylePreset: 'Stylized 3D Animation',
    defaultLocations: ['Warm Morning Kitchen Counter', 'Cluttered Creative Office Desk'],
    isPinned: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'preset-cinematic-drama',
    name: 'Dark Cinematic Crime / Series Drama',
    nicheType: 'cinematic_drama',
    description: 'High-stakes two-character confrontation with shot-reverse-shot cuts, chiaroscuro shadow play, and ruthless psychological tension.',
    personaSubjectAnchor: '30yo sharp-featured strategist with tailored dark wool coat, piercing gaze, paired against an equally poised rival.',
    cameraShootingStyle: 'Anamorphic 35mm cinema lens, 24fps motion cadence, tight shot-reverse-shot framing, cold moody rim light with deep blacks.',
    hookArchetype: 'cold_open_standoff',
    pacingCadence: 'measured_cinematic_16w',
    audioFoleyMood: 'Deep cinematic sub-bass drone, rain hitting window glass, directional dialogue resonance, tension riser.',
    visualStylePreset: 'Moody Film Noir',
    defaultLocations: ['Penthouse Study at Night', 'Dimly Lit Underground Vault'],
    isPinned: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'preset-faceless-aesthetic',
    name: 'High-Retention Faceless / Stoic Aesthetic',
    nicheType: 'faceless_aesthetic',
    description: 'Hypnotic slow-motion aesthetic scenes, anonymous silhouette framing, poetic philosophical voiceovers with maximum save-rates.',
    personaSubjectAnchor: 'Anonymous lone figure silhouette in long dark trench coat, back turned or shadow-obscured face, walking purposefully through atmospheric rain.',
    cameraShootingStyle: 'Slow-motion 60fps tracking shot, smooth cinematic gimbal glide, 85mm anamorphic portrait framing, neon reflections in wet asphalt.',
    hookArchetype: 'secret_expose',
    pacingCadence: 'ambient_voiceover_12w',
    audioFoleyMood: 'Deep resonant voiceover, rain and thunder Foley, atmospheric synth pad, slow emotional piano chords.',
    visualStylePreset: 'Hyper-Realistic Cinematic',
    defaultLocations: ['Rain-Drenched Midnight Cyberpunk City', 'Foggy Mountain Overlook at Sunrise'],
    isPinned: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'preset-podcast-debate',
    name: 'High-Ticket Podcast & Contrarian Debate',
    nicheType: 'podcast_debate',
    description: 'Studio multi-cam setup with Shure SM7B microphones, debate dynamics, contrarian industry secrets, and polarizing insights.',
    personaSubjectAnchor: '32yo charismatic host with black studio headphones and grey hoodie, debating with a 40yo veteran investor in navy blazer.',
    cameraShootingStyle: 'Studio multi-cam 3-point lighting, 50mm portrait lens, Shure mic boom arm in foreground corner, dark acoustic foam backdrop.',
    hookArchetype: 'controversial_opinion',
    pacingCadence: 'rapid_tiktok_22w',
    audioFoleyMood: 'Studio vocal presence, boom arm desk vibration, subtle chair swivel Foley, room acoustic treatment.',
    visualStylePreset: 'Hyper-Realistic Cinematic',
    defaultLocations: ['Modern Dark Acoustic Podcast Studio'],
    isPinned: false,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];
